In [1]:
import numpy as np


In [2]:
array1 = np.array([1,2,3,4,5])

In [3]:
array2 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])


In [4]:
print(array1)

[1 2 3 4 5]


In [5]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
array3 = np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
],
                  [
                  [16,17,18,19,20],
                  [21,22,23,24,25],
                  [26,27,28,29,30]
                  ]])

In [7]:
print(array3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [9]:
array4 = np.zeros((5,4))

In [10]:
print(array4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
array5 = np.zeros((2,5,4))

In [12]:
print(array5)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [13]:
array5 = np.ones((2,5,4))

In [14]:
print(array5)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [16]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
array6 = np.linspace(1,10,79)
print(array6)

[ 1.          1.11538462  1.23076923  1.34615385  1.46153846  1.57692308
  1.69230769  1.80769231  1.92307692  2.03846154  2.15384615  2.26923077
  2.38461538  2.5         2.61538462  2.73076923  2.84615385  2.96153846
  3.07692308  3.19230769  3.30769231  3.42307692  3.53846154  3.65384615
  3.76923077  3.88461538  4.          4.11538462  4.23076923  4.34615385
  4.46153846  4.57692308  4.69230769  4.80769231  4.92307692  5.03846154
  5.15384615  5.26923077  5.38461538  5.5         5.61538462  5.73076923
  5.84615385  5.96153846  6.07692308  6.19230769  6.30769231  6.42307692
  6.53846154  6.65384615  6.76923077  6.88461538  7.          7.11538462
  7.23076923  7.34615385  7.46153846  7.57692308  7.69230769  7.80769231
  7.92307692  8.03846154  8.15384615  8.26923077  8.38461538  8.5
  8.61538462  8.73076923  8.84615385  8.96153846  9.07692308  9.19230769
  9.30769231  9.42307692  9.53846154  9.65384615  9.76923077  9.88461538
 10.        ]


In [18]:
array6 = np.linspace(1,10,5)
print(array6)

[ 1.    3.25  5.5   7.75 10.  ]


In [19]:
array3.ndim

3

In [20]:
array3.shape

(2, 3, 5)

In [21]:
array3.size

30